# -*- coding: utf-8 -*-
"""task2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zjWAeL_J81vcFk4N5-_Ntpyz2SFBNcJn

# **WAP to enter a number from user and print its absolute value.**
"""

# Taking user input
num = float(input("Enter a number: "))

# Printing absolute value
print("Absolute value:", abs(num))

"""# **WAP to enter a year from user and check if it is leap year or not.**"""

# Taking year input from user
year = int(input("Enter a year: "))

# Checking if the year is a leap year
if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(year, "is a Leap Year")
else:
    print(year, "is Not a Leap Year")

"""# **WAP to enter the age of 3 person and print oldest and yougest among them.**"""

# Taking input for ages of three persons
age1 = int(input("Enter age of first person: "))
age2 = int(input("Enter age of second person: "))
age3 = int(input("Enter age of third person: "))

# Finding the oldest and youngest
oldest = max(age1, age2, age3)
youngest = min(age1, age2, age3)

# Printing the results
print("Oldest person's age:", oldest)
print("Youngest person's age:", youngest)

"""# **Write a program that asks the user to enter a series of numbers. The program should ask for numbers until the user enters a negative number. Once the user enters a negative number, the program should stop and print the sum of all the positive numbers entered**
# **Example**
# **Enter a number: 5**
# **Enter a number: 8**
# **Enter a number: 12**
# **Enter a number: -2**
# **The sum of the positive numbers is 25.**
"""

# Initialize sum variable
total = 0

while True:
    num = int(input("Enter a number: "))  # Take user input

    if num < 0:  # Check if the number is negative
        break  # Exit the loop

    total += num  # Add positive numbers to total

# Print the sum of positive numbers
print("The sum of the positive numbers is", total)

"""# **Write a program that asks the user to enter their name and age. The program should check if the user's age is greater than or equal to 18. If it is, the program should print a message saying they are eligible to vote. Otherwise, the program should print a message saying they are not eligible to vote due to being underage.**"""

# Taking user input
name = input("Enter your name: ")
age = int(input("Enter your age: "))

# Checking voting eligibility
if age >= 18:
    print(f"Hello {name}, you are eligible to vote! ✅")
else:
    print(f"Sorry {name}, you are not eligible to vote as you are under 18. ❌")

"""# **Write a Python Program to Find the Factorial of a Number**"""

# Taking user input
num = int(input("Enter a number: "))

# Checking if the number is negative
if num < 0:
    print("Factorial is not defined for negative numbers.")
else:
    factorial = 1
    for i in range(1, num + 1):
        factorial *= i  # Multiply each number

    print(f"The factorial of {num} is {factorial}")